_wandb:
    value:
        cli_version: 0.19.6
        code_path: code/mechagogue/examples/maxnist/train_mutable_maxnist_ga.py
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 12
                - 55
            "2":
                - 12
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
